### ISSUE TITLE
Server Deadlock due to BigReactors

### ISSUE THREAD

**Issue by Rubbertjuh** [CyberdyneCC/BigReactors-1.7.10#20]
`RUNNABLE
    at erogenousbeef.core.multiblock.MultiblockControllerBase.selectNewReferenceCoord(MultiblockControllerBase.java:853)
    at erogenousbeef.core.multiblock.MultiblockControllerBase.detachBlock(MultiblockControllerBase.java:237)
    at erogenousbeef.core.multiblock.MultiblockTileEntityBase.detachSelf(MultiblockTileEntityBase.java:348)
    at erogenousbeef.core.multiblock.MultiblockTileEntityBase.onChunkUnload(MultiblockTileEntityBase.java:137)
    at net.minecraft.world.World.func_72939_s(World.java:2533)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
    at java.lang.Thread.run(Thread.java:745)`

Running Tekkit Legends modpack - BigReactors-0.4.3A version that fixes the client meta data crash. 
Would love to pay a nice amount to fix this issue if this helps you :)

**Comment by XFactHD** [comment]
What server software are you using?

**Comment by Rubbertjuh** [comment]
Latest Thermos

**Comment by XFactHD** [comment]
As I have no experience with Thermos I will call in @Robotia for that one.

**Comment by Rubbertjuh** [comment]
Thank you, looking forward hearing more of this issue
